### PR TITLE
minor change

### PR DESCRIPTION
**Pull request by Ravencentric**

### CODE REVIEW

**Comment by animetosho** [comment]
I assume this was made in accident, though I could enable that as an option if people are interested...

**Comment by Ravencentric** [comment]
Yes it was indeed an accident. Didn't wanna PR my hacky edit since I don't really know js. There's also another fork that does it better here https://github.com/x-cord/Nyuu. Would love to see these improved obfuscation in Nyuu.

**Comment by animetosho** [comment]
Thanks for the pointer!

I might need an issue raised for explaining some of those changes, if the author is interested, otherwise they could just keep it in their fork.

**Comment by Ravencentric** [comment]
@animetosho so I tried testing the master build, and I can't seem to replicate the same results as my hacky changes. What would the command look like to replicate both the filename and from obfuscation?

This what what i tested
```
--from '${rand(13)}@${rand(5)}.${rand(3)}' --subject '${rand(20)}' --header name='${rand(20)}'
```

**Comment by animetosho** [comment]
`--filename` is probably where you want to look, though the way it works is different from your edit.

**Comment by Ravencentric** [comment]
I tried `--filename` and it ended up obfuscating it inside the .nzb file as well. Is there a way to obfuscate it for article lookup but write the unobfuscated filename in the nzb file itself?

**Comment by animetosho** [comment]
I just added `--yenc-name` (use instead of `--filename`) which is probably closer to what you want.

**Comment by Ravencentric** [comment]
--yenc-name is perfect! thank you!

**Pull request closed without merging**
